In [15]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from MCMC_VMP import MCMC_VMP
from UMMM import UMMM

In [16]:
np.random.seed(0)

In [17]:
N, K = 1000, 5

print(f'Número dos observações: {N}\n')

print(f'Número das categorias latentes: {K}')

Número dos observações: 1000

Número das categorias latentes: 5


In [ ]:
nt = 10

pvals = np.random.dirichlet(alpha = [nt/K]*K)

print(f'Número de experimentos: {nt}\n')

print(f'Probabilidade das categorias latentes:\n')

print(pvals)

Número de experimentos: 10

Probabilidade das categorias latentes:

[0.34172383 0.14885535 0.36089549 0.04632187 0.10220345]


In [19]:
Z = np.random.multinomial(n = N, pvals = [1/K]*K)

print('Número de observações por categoria: \n')

print(Z)

Número de observações por categoria: 

[207 158 215 190 230]


In [20]:
Dados = {'X': [], 'Z': []}

for k in range(K):

    Dados['X'] += list(np.random.binomial(n = nt, p = pvals[k], size = Z[k]))

    Dados['Z'] += [k]*Z[k]

Dados = pd.DataFrame(Dados)

Dados.head()

X  Z
0  6  0
1  3  0
2  3  0
3  2  0
4  5  0

In [23]:
Modelo = MCMC_VMP(

    Dados = np.array(Dados['X']).reshape((-1, 1)), Categorias = K, 
    
    nu_0 = 1e-6, chi_0 = np.array([0]), 
    
    Distribuicao = UMMM(NT = nt),

    Amostra = 10, Descartadas = 20

)

Modelo.estima_modelo(num = 50)

In [24]:
print(1/(1 + np.exp(-Modelo.eta)))

[[0.24914785]
 [0.03198936]
 [0.19776766]
 [0.43109268]
 [0.12204382]]
